backend:
  name: github
  repo: vitaliyoskalenko/taskme          # ← must be exact: username/repo-name
  branch: main                                    # your default branch
  base_url: https://docs-taskme-auth.netlify.app   
  auth_endpoint: auth

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}