backend:
  name: github
  repo: vitaliyoskalenko/taskme
  branch: main
  base_url: https://docs-taskme.netlify.app
  auth_endpoint: oauth/authorize 
  token_endpoint: oauth/access_token

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}